name: daily-umami-report

on:
  schedule:
    - cron: '30 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  umamiReportJob:
    name: daily umami report
    runs-on: ubuntu-latest

    outputs:
      umami_page_views: ${{ steps.umamiReportStep.outputs.pageViews }}
      umami_report_file: ${{ steps.umamiReportStep.outputs.umamiReportFile }}
      umami_report: ${{ steps.umamiReport.outputs.umamiReport }}
      umami_one_line_report: ${{ steps.umamiReport.outputs.umamiOneLineReport }}
    steps:
      - name: Create Daily Umami report
        id: umamiReportStep
        uses: boly38/action-umami-report@main
        with:
          umami-server: https://${{secrets.UMAMI_SERVER}}
          umami-user: ${{secrets.UMAMI_USERNAME}}
          umami-password: ${{secrets.UMAMI_PASSWORD}}
          umami-site-domain: ${{secrets.UMAMI_SITE_DOMAIN}}
          umami-report-file: 'umamiReport.md'
          umami-report-content: pageviews|events|urls
          umami-period: 24h
          umami-unit: hour
          umami-tz: Asia/Shanghai
        env:
          UMAMI_CLIENT_TIMEOUT_MS: 5000
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          publish_dir: ./umami
          external_repository: i-abc/blog-timeline
          publish_branch: main
          destination_dir: umami
          commit_message: ${{ github.event.head_commit.message }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
